// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SocialClub.Web.Models
{
    public partial class ClubEvent
    {
        public int EventId { get; set; }
        public string EventName { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string Venue { get; set; }
        public string HostName { get; set; }
        public string EventStatus { get; set; }
        public string EventDescription { get; set; }
    }
}